receivers:
  mongodb:
    hosts:
      - endpoint: # Required parameter
    collection_interval: # Required parameter
    username: # Required secret
    password: # Required secret
    initial_delay: # Optional parameter # valid units ns, us (or Âµs), ms, s, m, h
    direct_connection: # Optional parameter
    replica_set: # Optional parameter
    timeout: # Optional parameter
    tls:
      insecure: # Required parameter
      insecure_skip_verify: # Required parameter
      server_name_override: # Optional parameter
      ca_file: # Optional parameter
      cert_file: # Optional parameter
      key_file: # Optional parameter
    metrics:
      mongodb.cache.operations:
        enabled: true
      mongodb.collection.count:
        enabled: true
      mongodb.data.size:
        enabled: true
      mongodb.connection.count:
        enabled: true
      mongodb.extent.count:
        enabled: true
      mongodb.global_lock.time:
        enabled: true
      mongodb.index.count:
        enabled: true
      mongodb.index.size:
        enabled: true
      mongodb.memory.usage:
        enabled: true
      mongodb.object.count:
        enabled: true
      mongodb.operation.latency.time:
        enabled: false
      mongodb.operation.count:
        enabled: true
      mongodb.operation.repl.count:
        enabled: false
      mongodb.storage.size:
        enabled: true
      mongodb.database.count:
        enabled: true
      mongodb.index.access.count:
        enabled: true
      mongodb.document.operation.count:
        enabled: true
      mongodb.network.io.receive:
        enabled: true
      mongodb.network.io.transmit:
        enabled: true
      mongodb.network.request.count:
        enabled: true
      mongodb.operation.time:
        enabled: true
      mongodb.session.count:
        enabled: true
      mongodb.cursor.count:
        enabled: true
      mongodb.cursor.timeout.count:
        enabled: true
      mongodb.lock.acquire.count:
        enabled: false
      mongodb.lock.acquire.wait_count:
        enabled: false
      mongodb.lock.acquire.time:
        enabled: false
      mongodb.lock.deadlock.count:
        enabled: false
      mongodb.health:
        enabled: false
      mongodb.uptime:
        enabled: false
      mongodb.repl_queries_per_sec:
        enabled: false
      mongodb.repl_inserts_per_sec:
        enabled: false
      mongodb.repl_commands_per_sec:
        enabled: false
      mongodb.repl_getmores_per_sec:
        enabled: false
      mongodb.repl_deletes_per_sec:
        enabled: false
      mongodb.repl_updates_per_sec:
        enabled: false
      mongodb.inserts.rate:
        enabled: false
      mongodb.commands.rate:
        enabled: false
      mongodb.getmores.rate:
        enabled: false
      mongodb.deletes.rate:
        enabled: false
      mongodb.updates.rate:
        enabled: false
      mongodb.flushes.rate:
        enabled: false
      mongodb.active.writes:
        enabled: false
      mongodb.active.reads:
        enabled: false
      mongodb.wtcache.bytes.read:
        enabled: false
      # enabling the metrics which are not enabled by default
      mongodb.page_faults:
        enabled: true
      mongodb.queries.rate:
        enabled: true
  # Optional receiver
  # filelog:
  #   include: # Required parameter
  #   start_at: end
  #   poll_interval: 5s

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 50
    spike_limit_percentage: 30
  solarwinds/mongodb:
    collector_attributes_decoration:
      enabled: true
      extension: solarwinds
    resource:
      sw.otelcol.receiver.name: "mongodb"
      sw.otelcol.integration.id: # Required parameter
  resourcedetection/ec2:
    detectors: ["ec2"]
    timeout: 2s
    override: true
  resourcedetection/azure:
    detectors: ["azure"]
    timeout: 2s
    override: true
  resourcedetection/gcp:
    detectors: ["gcp"]
    timeout: 2s
    override: true
  resourcedetection/system:
    detectors: ["system"]
    timeout: 2s
    override: false
    system:
      hostname_sources: ["os"]
  batch:
    send_batch_max_size: 20000

extensions:
  solarwinds:
    collector_name: # Required parameter
    grpc: &grpc_settings
      endpoint: # Required parameter
      tls:
        insecure: false
      headers: {"Authorization": "Bearer ${env:SOLARWINDS_TOKEN}"}

exporters:
  otlp:
    <<: *grpc_settings

service:
  extensions:
    - solarwinds
  pipelines:
    metrics/mongodb:
      receivers:
        - mongodb
      processors:
        - memory_limiter
        - resourcedetection/ec2
        - resourcedetection/azure
        - resourcedetection/gcp
        - resourcedetection/system
        - batch
        - solarwinds/mongodb
      exporters:
        - otlp

    # Optional pipeline
    # logs/mongodb:
    #   receivers:
    #     - filelog
    #   processors:
    #     - memory_limiter
    #     - resourcedetection/ec2
    #     - resourcedetection/azure
    #     - resourcedetection/gcp
    #     - resourcedetection/system
    #     - batch
    #     - solarwinds/mongodb
    #   exporters:
    #     - otlp
